name       : ifuse
version    : 1.1.4
release    : 6
source     :
    - https://github.com/libimobiledevice/ifuse/releases/download/1.1.4/ifuse-1.1.4.tar.bz2 : 3550702ef94b2f5f16c7db91c6b3282b2aed1340665834a03e47458e09d98d87
license    : LGPL-2.1-or-later
component  : multimedia-library
summary    : A fuse filesystem implementation to access the contents of iOS devices.
description: |
    A fuse filesystem implementation to access the contents of iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(fuse)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
