name       : ifuse
version    : 1.1.3
release    : 4
source     :
    - https://github.com/libimobiledevice/ifuse/archive/1.1.3.tar.gz : 9b63afa6f2182da9e8c04b9e5a25c509f16f96f5439a271413956ecb67143089
license    : LGPL-2.1-or-later
component  : multimedia-library
summary    : A fuse filesystem implementation to access the contents of iOS devices.
description: |
    A fuse filesystem implementation to access the contents of iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(fuse)
    - pkgconfig(libplist)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
