name       : ifuse
version    : 1.1.3
release    : 2
source     :
    - http://www.libimobiledevice.org/downloads/ifuse-1.1.3.tar.bz2 : a788de66fb7720c84a5a775df415f78bbfb7c467a76c732d23292c6986252add
license    : LGPL-2.1
summary    : A fuse filesystem implementation to access the contents of iOS devices.
description: |
    A fuse filesystem implementation to access the contents of iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(fuse)
    - pkgconfig(libplist)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
